#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCF")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBan(tblBan instance);
    partial void UpdatetblBan(tblBan instance);
    partial void DeletetblBan(tblBan instance);
    partial void InserttblChiTietPhieuNhap(tblChiTietPhieuNhap instance);
    partial void UpdatetblChiTietPhieuNhap(tblChiTietPhieuNhap instance);
    partial void DeletetblChiTietPhieuNhap(tblChiTietPhieuNhap instance);
    partial void InserttblChiTietPhieuXuat(tblChiTietPhieuXuat instance);
    partial void UpdatetblChiTietPhieuXuat(tblChiTietPhieuXuat instance);
    partial void DeletetblChiTietPhieuXuat(tblChiTietPhieuXuat instance);
    partial void InserttblDVT(tblDVT instance);
    partial void UpdatetblDVT(tblDVT instance);
    partial void DeletetblDVT(tblDVT instance);
    partial void InserttblKhuVuc(tblKhuVuc instance);
    partial void UpdatetblKhuVuc(tblKhuVuc instance);
    partial void DeletetblKhuVuc(tblKhuVuc instance);
    partial void InserttblMatHang(tblMatHang instance);
    partial void UpdatetblMatHang(tblMatHang instance);
    partial void DeletetblMatHang(tblMatHang instance);
    partial void InserttblNhaCungCap(tblNhaCungCap instance);
    partial void UpdatetblNhaCungCap(tblNhaCungCap instance);
    partial void DeletetblNhaCungCap(tblNhaCungCap instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    partial void InserttblPhieuNhap(tblPhieuNhap instance);
    partial void UpdatetblPhieuNhap(tblPhieuNhap instance);
    partial void DeletetblPhieuNhap(tblPhieuNhap instance);
    partial void InserttblPhieuXuat(tblPhieuXuat instance);
    partial void UpdatetblPhieuXuat(tblPhieuXuat instance);
    partial void DeletetblPhieuXuat(tblPhieuXuat instance);
    partial void InserttblTaiKhoan(tblTaiKhoan instance);
    partial void UpdatetblTaiKhoan(tblTaiKhoan instance);
    partial void DeletetblTaiKhoan(tblTaiKhoan instance);
    #endregion
		
		public dbDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLCFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBan> tblBans
		{
			get
			{
				return this.GetTable<tblBan>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietPhieuNhap> tblChiTietPhieuNhaps
		{
			get
			{
				return this.GetTable<tblChiTietPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietPhieuXuat> tblChiTietPhieuXuats
		{
			get
			{
				return this.GetTable<tblChiTietPhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<tblDVT> tblDVTs
		{
			get
			{
				return this.GetTable<tblDVT>();
			}
		}
		
		public System.Data.Linq.Table<tblKhuVuc> tblKhuVucs
		{
			get
			{
				return this.GetTable<tblKhuVuc>();
			}
		}
		
		public System.Data.Linq.Table<tblMatHang> tblMatHangs
		{
			get
			{
				return this.GetTable<tblMatHang>();
			}
		}
		
		public System.Data.Linq.Table<tblNhaCungCap> tblNhaCungCaps
		{
			get
			{
				return this.GetTable<tblNhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblPhieuNhap> tblPhieuNhaps
		{
			get
			{
				return this.GetTable<tblPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<tblPhieuXuat> tblPhieuXuats
		{
			get
			{
				return this.GetTable<tblPhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this.GetTable<tblTaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBan")]
	public partial class tblBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenBan;
		
		private System.Nullable<int> _SoGhe;
		
		private System.Nullable<byte> _DangSuDung;
		
		private System.Nullable<int> _IdKV;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntitySet<tblPhieuXuat> _tblPhieuXuats;
		
		private EntityRef<tblKhuVuc> _tblKhuVuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenBanChanging(string value);
    partial void OnTenBanChanged();
    partial void OnSoGheChanging(System.Nullable<int> value);
    partial void OnSoGheChanged();
    partial void OnDangSuDungChanging(System.Nullable<byte> value);
    partial void OnDangSuDungChanged();
    partial void OnIdKVChanging(System.Nullable<int> value);
    partial void OnIdKVChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblBan()
		{
			this._tblPhieuXuats = new EntitySet<tblPhieuXuat>(new Action<tblPhieuXuat>(this.attach_tblPhieuXuats), new Action<tblPhieuXuat>(this.detach_tblPhieuXuats));
			this._tblKhuVuc = default(EntityRef<tblKhuVuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBan", DbType="NVarChar(50)")]
		public string TenBan
		{
			get
			{
				return this._TenBan;
			}
			set
			{
				if ((this._TenBan != value))
				{
					this.OnTenBanChanging(value);
					this.SendPropertyChanging();
					this._TenBan = value;
					this.SendPropertyChanged("TenBan");
					this.OnTenBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGhe", DbType="Int")]
		public System.Nullable<int> SoGhe
		{
			get
			{
				return this._SoGhe;
			}
			set
			{
				if ((this._SoGhe != value))
				{
					this.OnSoGheChanging(value);
					this.SendPropertyChanging();
					this._SoGhe = value;
					this.SendPropertyChanged("SoGhe");
					this.OnSoGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangSuDung", DbType="TinyInt")]
		public System.Nullable<byte> DangSuDung
		{
			get
			{
				return this._DangSuDung;
			}
			set
			{
				if ((this._DangSuDung != value))
				{
					this.OnDangSuDungChanging(value);
					this.SendPropertyChanging();
					this._DangSuDung = value;
					this.SendPropertyChanged("DangSuDung");
					this.OnDangSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKV", DbType="Int")]
		public System.Nullable<int> IdKV
		{
			get
			{
				return this._IdKV;
			}
			set
			{
				if ((this._IdKV != value))
				{
					if (this._tblKhuVuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKVChanging(value);
					this.SendPropertyChanging();
					this._IdKV = value;
					this.SendPropertyChanged("IdKV");
					this.OnIdKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBan_tblPhieuXuat", Storage="_tblPhieuXuats", ThisKey="Id", OtherKey="IdBan")]
		public EntitySet<tblPhieuXuat> tblPhieuXuats
		{
			get
			{
				return this._tblPhieuXuats;
			}
			set
			{
				this._tblPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhuVuc_tblBan", Storage="_tblKhuVuc", ThisKey="IdKV", OtherKey="Id", IsForeignKey=true)]
		public tblKhuVuc tblKhuVuc
		{
			get
			{
				return this._tblKhuVuc.Entity;
			}
			set
			{
				tblKhuVuc previousValue = this._tblKhuVuc.Entity;
				if (((previousValue != value) 
							|| (this._tblKhuVuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhuVuc.Entity = null;
						previousValue.tblBans.Remove(this);
					}
					this._tblKhuVuc.Entity = value;
					if ((value != null))
					{
						value.tblBans.Add(this);
						this._IdKV = value.Id;
					}
					else
					{
						this._IdKV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblKhuVuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuXuats(tblPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblBan = this;
		}
		
		private void detach_tblPhieuXuats(tblPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietPhieuNhap")]
	public partial class tblChiTietPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdPN;
		
		private int _IdMatHang;
		
		private System.Nullable<int> _SL;
		
		private System.Nullable<int> _GiaNhap;
		
		private EntityRef<tblMatHang> _tblMatHang;
		
		private EntityRef<tblPhieuNhap> _tblPhieuNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPNChanging(long value);
    partial void OnIdPNChanged();
    partial void OnIdMatHangChanging(int value);
    partial void OnIdMatHangChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnGiaNhapChanging(System.Nullable<int> value);
    partial void OnGiaNhapChanged();
    #endregion
		
		public tblChiTietPhieuNhap()
		{
			this._tblMatHang = default(EntityRef<tblMatHang>);
			this._tblPhieuNhap = default(EntityRef<tblPhieuNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPN", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IdPN
		{
			get
			{
				return this._IdPN;
			}
			set
			{
				if ((this._IdPN != value))
				{
					if (this._tblPhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPNChanging(value);
					this.SendPropertyChanging();
					this._IdPN = value;
					this.SendPropertyChanged("IdPN");
					this.OnIdPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMatHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdMatHang
		{
			get
			{
				return this._IdMatHang;
			}
			set
			{
				if ((this._IdMatHang != value))
				{
					if (this._tblMatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMatHangChanging(value);
					this.SendPropertyChanging();
					this._IdMatHang = value;
					this.SendPropertyChanged("IdMatHang");
					this.OnIdMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNhap", DbType="Int")]
		public System.Nullable<int> GiaNhap
		{
			get
			{
				return this._GiaNhap;
			}
			set
			{
				if ((this._GiaNhap != value))
				{
					this.OnGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._GiaNhap = value;
					this.SendPropertyChanged("GiaNhap");
					this.OnGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMatHang_tblChiTietPhieuNhap", Storage="_tblMatHang", ThisKey="IdMatHang", OtherKey="Id", IsForeignKey=true)]
		public tblMatHang tblMatHang
		{
			get
			{
				return this._tblMatHang.Entity;
			}
			set
			{
				tblMatHang previousValue = this._tblMatHang.Entity;
				if (((previousValue != value) 
							|| (this._tblMatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMatHang.Entity = null;
						previousValue.tblChiTietPhieuNhaps.Remove(this);
					}
					this._tblMatHang.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieuNhaps.Add(this);
						this._IdMatHang = value.Id;
					}
					else
					{
						this._IdMatHang = default(int);
					}
					this.SendPropertyChanged("tblMatHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhieuNhap_tblChiTietPhieuNhap", Storage="_tblPhieuNhap", ThisKey="IdPN", OtherKey="Id", IsForeignKey=true)]
		public tblPhieuNhap tblPhieuNhap
		{
			get
			{
				return this._tblPhieuNhap.Entity;
			}
			set
			{
				tblPhieuNhap previousValue = this._tblPhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._tblPhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhieuNhap.Entity = null;
						previousValue.tblChiTietPhieuNhaps.Remove(this);
					}
					this._tblPhieuNhap.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieuNhaps.Add(this);
						this._IdPN = value.Id;
					}
					else
					{
						this._IdPN = default(long);
					}
					this.SendPropertyChanged("tblPhieuNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietPhieuXuat")]
	public partial class tblChiTietPhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdPX;
		
		private int _IdMH;
		
		private System.Nullable<int> _SL;
		
		private System.Nullable<int> _DonGia;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntityRef<tblMatHang> _tblMatHang;
		
		private EntityRef<tblPhieuXuat> _tblPhieuXuat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPXChanging(long value);
    partial void OnIdPXChanged();
    partial void OnIdMHChanging(int value);
    partial void OnIdMHChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblChiTietPhieuXuat()
		{
			this._tblMatHang = default(EntityRef<tblMatHang>);
			this._tblPhieuXuat = default(EntityRef<tblPhieuXuat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPX", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IdPX
		{
			get
			{
				return this._IdPX;
			}
			set
			{
				if ((this._IdPX != value))
				{
					if (this._tblPhieuXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPXChanging(value);
					this.SendPropertyChanging();
					this._IdPX = value;
					this.SendPropertyChanged("IdPX");
					this.OnIdPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdMH
		{
			get
			{
				return this._IdMH;
			}
			set
			{
				if ((this._IdMH != value))
				{
					if (this._tblMatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMHChanging(value);
					this.SendPropertyChanging();
					this._IdMH = value;
					this.SendPropertyChanged("IdMH");
					this.OnIdMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMatHang_tblChiTietPhieuXuat", Storage="_tblMatHang", ThisKey="IdMH", OtherKey="Id", IsForeignKey=true)]
		public tblMatHang tblMatHang
		{
			get
			{
				return this._tblMatHang.Entity;
			}
			set
			{
				tblMatHang previousValue = this._tblMatHang.Entity;
				if (((previousValue != value) 
							|| (this._tblMatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMatHang.Entity = null;
						previousValue.tblChiTietPhieuXuats.Remove(this);
					}
					this._tblMatHang.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieuXuats.Add(this);
						this._IdMH = value.Id;
					}
					else
					{
						this._IdMH = default(int);
					}
					this.SendPropertyChanged("tblMatHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhieuXuat_tblChiTietPhieuXuat", Storage="_tblPhieuXuat", ThisKey="IdPX", OtherKey="Id", IsForeignKey=true)]
		public tblPhieuXuat tblPhieuXuat
		{
			get
			{
				return this._tblPhieuXuat.Entity;
			}
			set
			{
				tblPhieuXuat previousValue = this._tblPhieuXuat.Entity;
				if (((previousValue != value) 
							|| (this._tblPhieuXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhieuXuat.Entity = null;
						previousValue.tblChiTietPhieuXuats.Remove(this);
					}
					this._tblPhieuXuat.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieuXuats.Add(this);
						this._IdPX = value.Id;
					}
					else
					{
						this._IdPX = default(long);
					}
					this.SendPropertyChanged("tblPhieuXuat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDVT")]
	public partial class tblDVT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ten;
		
		private EntitySet<tblMatHang> _tblMatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    #endregion
		
		public tblDVT()
		{
			this._tblMatHangs = new EntitySet<tblMatHang>(new Action<tblMatHang>(this.attach_tblMatHangs), new Action<tblMatHang>(this.detach_tblMatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(20)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDVT_tblMatHang", Storage="_tblMatHangs", ThisKey="Id", OtherKey="DonViTinh")]
		public EntitySet<tblMatHang> tblMatHangs
		{
			get
			{
				return this._tblMatHangs;
			}
			set
			{
				this._tblMatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblMatHangs(tblMatHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDVT = this;
		}
		
		private void detach_tblMatHangs(tblMatHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDVT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhuVuc")]
	public partial class tblKhuVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenKhuVuc;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntitySet<tblBan> _tblBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenKhuVucChanging(string value);
    partial void OnTenKhuVucChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblKhuVuc()
		{
			this._tblBans = new EntitySet<tblBan>(new Action<tblBan>(this.attach_tblBans), new Action<tblBan>(this.detach_tblBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhuVuc", DbType="NVarChar(50)")]
		public string TenKhuVuc
		{
			get
			{
				return this._TenKhuVuc;
			}
			set
			{
				if ((this._TenKhuVuc != value))
				{
					this.OnTenKhuVucChanging(value);
					this.SendPropertyChanging();
					this._TenKhuVuc = value;
					this.SendPropertyChanged("TenKhuVuc");
					this.OnTenKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhuVuc_tblBan", Storage="_tblBans", ThisKey="Id", OtherKey="IdKV")]
		public EntitySet<tblBan> tblBans
		{
			get
			{
				return this._tblBans;
			}
			set
			{
				this._tblBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBans(tblBan entity)
		{
			this.SendPropertyChanging();
			entity.tblKhuVuc = this;
		}
		
		private void detach_tblBans(tblBan entity)
		{
			this.SendPropertyChanging();
			entity.tblKhuVuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMatHang")]
	public partial class tblMatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenMatHang;
		
		private System.Nullable<int> _DonViTinh;
		
		private System.Nullable<int> _GiaBan;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntitySet<tblChiTietPhieuNhap> _tblChiTietPhieuNhaps;
		
		private EntitySet<tblChiTietPhieuXuat> _tblChiTietPhieuXuats;
		
		private EntityRef<tblDVT> _tblDVT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenMatHangChanging(string value);
    partial void OnTenMatHangChanged();
    partial void OnDonViTinhChanging(System.Nullable<int> value);
    partial void OnDonViTinhChanged();
    partial void OnGiaBanChanging(System.Nullable<int> value);
    partial void OnGiaBanChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblMatHang()
		{
			this._tblChiTietPhieuNhaps = new EntitySet<tblChiTietPhieuNhap>(new Action<tblChiTietPhieuNhap>(this.attach_tblChiTietPhieuNhaps), new Action<tblChiTietPhieuNhap>(this.detach_tblChiTietPhieuNhaps));
			this._tblChiTietPhieuXuats = new EntitySet<tblChiTietPhieuXuat>(new Action<tblChiTietPhieuXuat>(this.attach_tblChiTietPhieuXuats), new Action<tblChiTietPhieuXuat>(this.detach_tblChiTietPhieuXuats));
			this._tblDVT = default(EntityRef<tblDVT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMatHang", DbType="NVarChar(100)")]
		public string TenMatHang
		{
			get
			{
				return this._TenMatHang;
			}
			set
			{
				if ((this._TenMatHang != value))
				{
					this.OnTenMatHangChanging(value);
					this.SendPropertyChanging();
					this._TenMatHang = value;
					this.SendPropertyChanged("TenMatHang");
					this.OnTenMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="Int")]
		public System.Nullable<int> DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					if (this._tblDVT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Int")]
		public System.Nullable<int> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMatHang_tblChiTietPhieuNhap", Storage="_tblChiTietPhieuNhaps", ThisKey="Id", OtherKey="IdMatHang")]
		public EntitySet<tblChiTietPhieuNhap> tblChiTietPhieuNhaps
		{
			get
			{
				return this._tblChiTietPhieuNhaps;
			}
			set
			{
				this._tblChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMatHang_tblChiTietPhieuXuat", Storage="_tblChiTietPhieuXuats", ThisKey="Id", OtherKey="IdMH")]
		public EntitySet<tblChiTietPhieuXuat> tblChiTietPhieuXuats
		{
			get
			{
				return this._tblChiTietPhieuXuats;
			}
			set
			{
				this._tblChiTietPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDVT_tblMatHang", Storage="_tblDVT", ThisKey="DonViTinh", OtherKey="Id", IsForeignKey=true)]
		public tblDVT tblDVT
		{
			get
			{
				return this._tblDVT.Entity;
			}
			set
			{
				tblDVT previousValue = this._tblDVT.Entity;
				if (((previousValue != value) 
							|| (this._tblDVT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDVT.Entity = null;
						previousValue.tblMatHangs.Remove(this);
					}
					this._tblDVT.Entity = value;
					if ((value != null))
					{
						value.tblMatHangs.Add(this);
						this._DonViTinh = value.Id;
					}
					else
					{
						this._DonViTinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDVT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieuNhaps(tblChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblMatHang = this;
		}
		
		private void detach_tblChiTietPhieuNhaps(tblChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblMatHang = null;
		}
		
		private void attach_tblChiTietPhieuXuats(tblChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblMatHang = this;
		}
		
		private void detach_tblChiTietPhieuXuats(tblChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblMatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhaCungCap")]
	public partial class tblNhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _TenNCC;
		
		private string _MST;
		
		private string _DienThoai;
		
		private string _DiaChi;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntitySet<tblPhieuNhap> _tblPhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnMSTChanging(string value);
    partial void OnMSTChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblNhaCungCap()
		{
			this._tblPhieuNhaps = new EntitySet<tblPhieuNhap>(new Action<tblPhieuNhap>(this.attach_tblPhieuNhaps), new Action<tblPhieuNhap>(this.detach_tblPhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(150)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MST", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MST
		{
			get
			{
				return this._MST;
			}
			set
			{
				if ((this._MST != value))
				{
					this.OnMSTChanging(value);
					this.SendPropertyChanging();
					this._MST = value;
					this.SendPropertyChanged("MST");
					this.OnMSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblPhieuNhap", Storage="_tblPhieuNhaps", ThisKey="Id", OtherKey="MaNCC")]
		public EntitySet<tblPhieuNhap> tblPhieuNhaps
		{
			get
			{
				return this._tblPhieuNhaps;
			}
			set
			{
				this._tblPhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuNhaps(tblPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = this;
		}
		
		private void detach_tblPhieuNhaps(tblPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ho;
		
		private string _TenDem;
		
		private string _Ten;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private EntitySet<tblPhieuXuat> _tblPhieuXuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHoChanging(string value);
    partial void OnHoChanged();
    partial void OnTenDemChanging(string value);
    partial void OnTenDemChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    #endregion
		
		public tblNhanVien()
		{
			this._tblPhieuXuats = new EntitySet<tblPhieuXuat>(new Action<tblPhieuXuat>(this.attach_tblPhieuXuats), new Action<tblPhieuXuat>(this.detach_tblPhieuXuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho", DbType="NVarChar(10)")]
		public string Ho
		{
			get
			{
				return this._Ho;
			}
			set
			{
				if ((this._Ho != value))
				{
					this.OnHoChanging(value);
					this.SendPropertyChanging();
					this._Ho = value;
					this.SendPropertyChanged("Ho");
					this.OnHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDem", DbType="NVarChar(20)")]
		public string TenDem
		{
			get
			{
				return this._TenDem;
			}
			set
			{
				if ((this._TenDem != value))
				{
					this.OnTenDemChanging(value);
					this.SendPropertyChanging();
					this._TenDem = value;
					this.SendPropertyChanged("TenDem");
					this.OnTenDemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(10)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblPhieuXuat", Storage="_tblPhieuXuats", ThisKey="Id", OtherKey="IdNV")]
		public EntitySet<tblPhieuXuat> tblPhieuXuats
		{
			get
			{
				return this._tblPhieuXuats;
			}
			set
			{
				this._tblPhieuXuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuXuats(tblPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblPhieuXuats(tblPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhieuNhap")]
	public partial class tblPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _MaNCC;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private System.Nullable<byte> _NhapKho;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntitySet<tblChiTietPhieuNhap> _tblChiTietPhieuNhaps;
		
		private EntityRef<tblNhaCungCap> _tblNhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnNhapKhoChanging(System.Nullable<byte> value);
    partial void OnNhapKhoChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblPhieuNhap()
		{
			this._tblChiTietPhieuNhaps = new EntitySet<tblChiTietPhieuNhap>(new Action<tblChiTietPhieuNhap>(this.attach_tblChiTietPhieuNhaps), new Action<tblChiTietPhieuNhap>(this.detach_tblChiTietPhieuNhaps));
			this._tblNhaCungCap = default(EntityRef<tblNhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(20)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblNhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhapKho", DbType="TinyInt")]
		public System.Nullable<byte> NhapKho
		{
			get
			{
				return this._NhapKho;
			}
			set
			{
				if ((this._NhapKho != value))
				{
					this.OnNhapKhoChanging(value);
					this.SendPropertyChanging();
					this._NhapKho = value;
					this.SendPropertyChanged("NhapKho");
					this.OnNhapKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhieuNhap_tblChiTietPhieuNhap", Storage="_tblChiTietPhieuNhaps", ThisKey="Id", OtherKey="IdPN")]
		public EntitySet<tblChiTietPhieuNhap> tblChiTietPhieuNhaps
		{
			get
			{
				return this._tblChiTietPhieuNhaps;
			}
			set
			{
				this._tblChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblPhieuNhap", Storage="_tblNhaCungCap", ThisKey="MaNCC", OtherKey="Id", IsForeignKey=true)]
		public tblNhaCungCap tblNhaCungCap
		{
			get
			{
				return this._tblNhaCungCap.Entity;
			}
			set
			{
				tblNhaCungCap previousValue = this._tblNhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tblNhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhaCungCap.Entity = null;
						previousValue.tblPhieuNhaps.Remove(this);
					}
					this._tblNhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tblPhieuNhaps.Add(this);
						this._MaNCC = value.Id;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tblNhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieuNhaps(tblChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblPhieuNhap = this;
		}
		
		private void detach_tblChiTietPhieuNhaps(tblChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblPhieuNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhieuXuat")]
	public partial class tblPhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<int> _IdBan;
		
		private System.Nullable<int> _IdNV;
		
		private System.Nullable<System.DateTime> _NgayBan;
		
		private System.Nullable<byte> _DaThanhToan;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private EntitySet<tblChiTietPhieuXuat> _tblChiTietPhieuXuats;
		
		private EntityRef<tblBan> _tblBan;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdBanChanging(System.Nullable<int> value);
    partial void OnIdBanChanged();
    partial void OnIdNVChanging(System.Nullable<int> value);
    partial void OnIdNVChanged();
    partial void OnNgayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanChanged();
    partial void OnDaThanhToanChanging(System.Nullable<byte> value);
    partial void OnDaThanhToanChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblPhieuXuat()
		{
			this._tblChiTietPhieuXuats = new EntitySet<tblChiTietPhieuXuat>(new Action<tblChiTietPhieuXuat>(this.attach_tblChiTietPhieuXuats), new Action<tblChiTietPhieuXuat>(this.detach_tblChiTietPhieuXuats));
			this._tblBan = default(EntityRef<tblBan>);
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBan", DbType="Int")]
		public System.Nullable<int> IdBan
		{
			get
			{
				return this._IdBan;
			}
			set
			{
				if ((this._IdBan != value))
				{
					if (this._tblBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdBanChanging(value);
					this.SendPropertyChanging();
					this._IdBan = value;
					this.SendPropertyChanged("IdBan");
					this.OnIdBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNV", DbType="Int")]
		public System.Nullable<int> IdNV
		{
			get
			{
				return this._IdNV;
			}
			set
			{
				if ((this._IdNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNVChanging(value);
					this.SendPropertyChanging();
					this._IdNV = value;
					this.SendPropertyChanged("IdNV");
					this.OnIdNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBan
		{
			get
			{
				return this._NgayBan;
			}
			set
			{
				if ((this._NgayBan != value))
				{
					this.OnNgayBanChanging(value);
					this.SendPropertyChanging();
					this._NgayBan = value;
					this.SendPropertyChanged("NgayBan");
					this.OnNgayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaThanhToan", DbType="TinyInt")]
		public System.Nullable<byte> DaThanhToan
		{
			get
			{
				return this._DaThanhToan;
			}
			set
			{
				if ((this._DaThanhToan != value))
				{
					this.OnDaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._DaThanhToan = value;
					this.SendPropertyChanged("DaThanhToan");
					this.OnDaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhieuXuat_tblChiTietPhieuXuat", Storage="_tblChiTietPhieuXuats", ThisKey="Id", OtherKey="IdPX")]
		public EntitySet<tblChiTietPhieuXuat> tblChiTietPhieuXuats
		{
			get
			{
				return this._tblChiTietPhieuXuats;
			}
			set
			{
				this._tblChiTietPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBan_tblPhieuXuat", Storage="_tblBan", ThisKey="IdBan", OtherKey="Id", IsForeignKey=true)]
		public tblBan tblBan
		{
			get
			{
				return this._tblBan.Entity;
			}
			set
			{
				tblBan previousValue = this._tblBan.Entity;
				if (((previousValue != value) 
							|| (this._tblBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBan.Entity = null;
						previousValue.tblPhieuXuats.Remove(this);
					}
					this._tblBan.Entity = value;
					if ((value != null))
					{
						value.tblPhieuXuats.Add(this);
						this._IdBan = value.Id;
					}
					else
					{
						this._IdBan = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblPhieuXuat", Storage="_tblNhanVien", ThisKey="IdNV", OtherKey="Id", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblPhieuXuats.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblPhieuXuats.Add(this);
						this._IdNV = value.Id;
					}
					else
					{
						this._IdNV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieuXuats(tblChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblPhieuXuat = this;
		}
		
		private void detach_tblChiTietPhieuXuats(tblChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tblPhieuXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTaiKhoan")]
	public partial class tblTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaNhanVien;
		
		private string _TenTaiKhoan;
		
		private string _TenHienThi;
		
		private string _MatKhau;
		
		private System.Nullable<int> _IsAdmin;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _NguoiTao;
		
		private string _NguoiCapNhat;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnTenHienThiChanging(string value);
    partial void OnTenHienThiChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnIsAdminChanging(System.Nullable<int> value);
    partial void OnIsAdminChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public tblTaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(50)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="VarChar(50)")]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHienThi", DbType="VarChar(50)")]
		public string TenHienThi
		{
			get
			{
				return this._TenHienThi;
			}
			set
			{
				if ((this._TenHienThi != value))
				{
					this.OnTenHienThiChanging(value);
					this.SendPropertyChanging();
					this._TenHienThi = value;
					this.SendPropertyChanged("TenHienThi");
					this.OnTenHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Int")]
		public System.Nullable<int> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="VarChar(30)")]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="VarChar(30)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
